[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF0032"
backgroundColor = "#F4F4F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1A1A"
base = "light"
